### PR TITLE
Make Modal draggable

### PR DESCRIPTION
**Pull request by VictoriaBeilsten-Edmands**

### CODE REVIEW

**Review by PeterC-DLS — COMMENTED** [review]
Works well. Is it possible to set the initial positions to the top of the component rather top of the browser window?

**Comment by VictoriaBeilsten-Edmands** [comment]
> Works well. Is it possible to set the initial positions to the top of the component rather top of the browser window?

Yes, I've changed to use relative position and placed it offset from the overflow menu.

**Comment by PeterC-DLS** [comment]
Have you updated this branch? The initial position is now in top-left corner of window rather than top-middle of plot component. The css suggests it's in `position: fixed` .

**Comment by VictoriaBeilsten-Edmands** [comment]
> Have you updated this branch? The initial position is now in top-left corner of window rather than top-middle of plot component. The css suggests it's in `position: fixed` .

It should be updated now.

**Review by PeterC-DLS — APPROVED** [review]

**Pull request merged**
