### PR TITLE
Simplify swagger page by importing API schema directly

### PR DESCRIPTION
**Pull request by PeterC-DLS**

### CODE REVIEW

**Review by VictoriaBeilsten-Edmands — COMMENTED** [review]
There are some warnings in the console:
`validateDOMNesting(...): <h4> cannot appear as a descendant of <p>`

**Comment by PeterC-DLS** [comment]
I think this is a blip that got fixed upstream. With fastapi 0.111.0, I don't see any warnings.

**Comment by VictoriaBeilsten-Edmands** [comment]
The error has gone now.

There is a new warning `Warning: ConnectedPlot: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`  Something to look at at soem point in a different PR.

**Review by VictoriaBeilsten-Edmands — APPROVED** [review]

**Comment by PeterC-DLS** [comment]
Can check after other PR merged.

**Pull request merged**
